-- Permitir estado CANCELLED en ORDER_STATUS_HISTORY (para cancelar pedidos).
-- Ejecutar como FABRICA en DBeaver si obtienes error de constraint al cancelar.

ALTER TABLE ORDER_STATUS_HISTORY DROP CONSTRAINT CHK_OSH_STATUS;
ALTER TABLE ORDER_STATUS_HISTORY ADD CONSTRAINT CHK_OSH_STATUS CHECK (
  STATUS IN ('INITIATED','PREPARING','SHIPPED','DELIVERED','CANCELLED')
);
COMMIT;
